services:

    bot:
        build: .
        container_name: bot
        volumes:
            - .:/src
        env_file:
            - .env
        depends_on:
            - redis

    redis:
        image: redis/redis-stack:7.4.0-v1
        container_name: bot-redis
        ports:
            - "6379:6379"
            - "8001:8001"

    loki:
        image: grafana/loki:3.4
        container_name: bot-loki
        ports:
            - 3100:3100
        volumes:
            - ./loki-config.yaml:/etc/loki/loki-config.yaml

    promtail:
        image: grafana/promtail:3.4
        container_name: bot-promtail
        command: -config.file=/etc/promtail/promtail-config.yaml
        volumes:
            - ./promtail-config.yaml:/etc/promtail/promtail-config.yaml
            - ./logs:/logs/

    grafana:
        image: grafana/grafana:11.5.0
        container_name: bot-grafana
        ports:
            - 80:3000
        volumes:
            - ./grafana/provisioning-datasources:/etc/grafana/provisioning/datasources
            - ./grafana/dashboards.yaml:/etc/grafana/provisioning/dashboards/main.yaml
            - ./grafana/provisioning-dashboards:/etc/grafana/provisioning/dashboards
        environment:
            - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER:-admin}
            - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD:-admin}
