version: "3"
services:

    telegram_bot:
        build: .
        container_name: bot
        env_file:
            - .env

    agent:
        image: grafana/agent:latest
        container_name: grafana-agent
        restart: always
        ports:
            - "9411:9411"
        volumes:
            - "./grafana/config.yaml:/etc/agent-config/agent.yaml:ro"
            - "/:/host/root:ro"
            - "/sys:/host/sys:ro"
            - "/proc:/host/proc:ro"
            - "/tmp/agent:/etc/agent"
        entrypoint:
            - /bin/grafana-agent
            - -config.file=/etc/agent-config/agent.yaml
            - -config.expand-env=true
            - -metrics.wal-directory=/tmp/agent/wal
        network_mode: "host"
        pid: "host"
        env_file:
            - .env
