metrics:
  wal_directory: /tmp/agent
  global:
    scrape_interval: 60s
    remote_write:
    - url: https://21a026b9-22d2-4926-9bf0-98ad13496816.metrics.cockpit.fr-par.scw.cloud/api/v1/push
      headers:
        "X-Token": 1qXVccCFdTIghgH9za9PN3YKiiH5-XA1qSC91u9JNbPkjoem1f-PsLJP9_DEqP_T

integrations:
  node_exporter:
    enabled: true
    rootfs_path: /host/root
    sysfs_path: /host/sys
    procfs_path: /host/proc
    # Anything not provided in the list below will be disabled by default
    set_collectors:
      - uname
      - cpu
      - loadavg
      - meminfo
      - filesystem
      - netdev
      - boottime
      - time
      - stat