metrics:
  wal_directory: /tmp/agent
  global:
    scrape_interval: 60s
    remote_write:
    - url: ${SCALEWAY_GRAFANA_METRICS_URL}
      headers:
        "X-Token": ${SCALEWAY_GRAFANA_TOKEN}

integrations:
  node_exporter:
    enabled: true
    rootfs_path: /host/root
    sysfs_path: /host/sys
    procfs_path: /host/proc
    # Anything not provided in the list below will be disabled by default
    set_collectors:
      - uname
      - cpu
      - loadavg
      - meminfo
      - filesystem
      - netdev
      - boottime
      - time
      - stat